/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripPlannerRouteImport } from './routes/trip-planner'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StationFinderRouteImport } from './routes/station-finder'
import { Route as StationFaresRouteImport } from './routes/station-fares'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DataSourcesRouteImport } from './routes/data-sources'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TripPlannerRoute = TripPlannerRouteImport.update({
  id: '/trip-planner',
  path: '/trip-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StationFinderRoute = StationFinderRouteImport.update({
  id: '/station-finder',
  path: '/station-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const StationFaresRoute = StationFaresRouteImport.update({
  id: '/station-fares',
  path: '/station-fares',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DataSourcesRoute = DataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/data-sources': typeof DataSourcesRoute
  '/privacy': typeof PrivacyRoute
  '/station-fares': typeof StationFaresRoute
  '/station-finder': typeof StationFinderRoute
  '/terms': typeof TermsRoute
  '/trip-planner': typeof TripPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/data-sources': typeof DataSourcesRoute
  '/privacy': typeof PrivacyRoute
  '/station-fares': typeof StationFaresRoute
  '/station-finder': typeof StationFinderRoute
  '/terms': typeof TermsRoute
  '/trip-planner': typeof TripPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/data-sources': typeof DataSourcesRoute
  '/privacy': typeof PrivacyRoute
  '/station-fares': typeof StationFaresRoute
  '/station-finder': typeof StationFinderRoute
  '/terms': typeof TermsRoute
  '/trip-planner': typeof TripPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/data-sources'
    | '/privacy'
    | '/station-fares'
    | '/station-finder'
    | '/terms'
    | '/trip-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/data-sources'
    | '/privacy'
    | '/station-fares'
    | '/station-finder'
    | '/terms'
    | '/trip-planner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/data-sources'
    | '/privacy'
    | '/station-fares'
    | '/station-finder'
    | '/terms'
    | '/trip-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  DataSourcesRoute: typeof DataSourcesRoute
  PrivacyRoute: typeof PrivacyRoute
  StationFaresRoute: typeof StationFaresRoute
  StationFinderRoute: typeof StationFinderRoute
  TermsRoute: typeof TermsRoute
  TripPlannerRoute: typeof TripPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trip-planner': {
      id: '/trip-planner'
      path: '/trip-planner'
      fullPath: '/trip-planner'
      preLoaderRoute: typeof TripPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station-finder': {
      id: '/station-finder'
      path: '/station-finder'
      fullPath: '/station-finder'
      preLoaderRoute: typeof StationFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/station-fares': {
      id: '/station-fares'
      path: '/station-fares'
      fullPath: '/station-fares'
      preLoaderRoute: typeof StationFaresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-sources': {
      id: '/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof DataSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  DataSourcesRoute: DataSourcesRoute,
  PrivacyRoute: PrivacyRoute,
  StationFaresRoute: StationFaresRoute,
  StationFinderRoute: StationFinderRoute,
  TermsRoute: TermsRoute,
  TripPlannerRoute: TripPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
